spring:
# PROFILES
  profiles:
    active: dev
# ROOT CONFIG
  application:
    name: game
  datasource:
    username: game
    password: game
    url: jdbc:postgresql://localhost:5432/game
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
